"""Generates app/data/kb.json (trilingual knowledge base). Edit here, then re-run:  python3 ml/build_kb.py
NOTE: Hindi/Marathi text should be reviewed by a native-speaking agriculture extension worker before field use."""
import json, os

def t(en, hi, mr): return {"en": en, "hi": hi, "mr": mr}

crops = {
 "tomato": t("Tomato", "टमाटर", "टोमॅटो"),
 "grape":  t("Grape", "अंगूर", "द्राक्ष"),
 "corn":   t("Maize", "मक्का", "मका"),
 "potato": t("Potato", "आलू", "बटाटा"),
 "pepper": t("Bell pepper", "शिमला मिर्च", "ढोबळी मिरची"),
}

S = {  # reusable advice snippets
 # ---- what to do now
 "do_remove_leaves": t("Pick off the worst-affected leaves and put them in a bag. Do not leave them in the field or in compost.",
                       "सबसे ज़्यादा प्रभावित पत्तियाँ तोड़कर थैली में रखें। उन्हें खेत में या खाद के ढेर में न छोड़ें।",
                       "सर्वात जास्त बाधित पाने तोडून पिशवीत ठेवा. ती शेतात किंवा कंपोस्टमध्ये टाकू नका."),
 "do_destroy_plants": t("Pull out and destroy badly infected plants so the problem does not reach healthy plants.",
                        "बुरी तरह संक्रमित पौधों को उखाड़कर नष्ट कर दें ताकि रोग स्वस्थ पौधों तक न पहुँचे।",
                        "जास्त बाधित झाडे उपटून नष्ट करा, म्हणजे रोग निरोगी झाडांपर्यंत पोहोचणार नाही."),
 "do_water_base": t("Water at the base of the plant, in the morning. Avoid wetting the leaves.",
                    "सुबह के समय पौधे की जड़ के पास पानी दें। पत्तियों को गीला न करें।",
                    "सकाळी झाडाच्या बुंध्याजवळ पाणी द्या. पाने ओली होऊ देऊ नका."),
 "do_no_wet_work": t("Do not walk through or work in the field while plants are wet. Hands, tools and clothes carry the disease.",
                     "पौधे गीले हों तब खेत में न चलें और काम न करें। हाथ, औज़ार और कपड़े रोग फैलाते हैं।",
                     "झाडे ओली असताना शेतात फिरू नका किंवा काम करू नका. हात, अवजारे आणि कपड्यांमुळे रोग पसरतो."),
 "do_expert": t("Show the plant to your Krishi Vigyan Kendra (KVK) or agriculture officer to get the right spray and dose for your crop. Always follow the product label.",
                "सही दवा और मात्रा के लिए पौधा अपने कृषि विज्ञान केंद्र (KVK) या कृषि अधिकारी को दिखाएँ। हमेशा दवा के लेबल के अनुसार ही प्रयोग करें।",
                "योग्य फवारणी व मात्रा जाणून घेण्यासाठी झाड तुमच्या कृषी विज्ञान केंद्रात (KVK) किंवा कृषी अधिकाऱ्यांना दाखवा. औषधाच्या लेबलवरील सूचनांनुसारच वापर करा."),
 "do_expert_urgent": t("Act today: contact your KVK or agriculture officer right away. This disease can ruin a field within days.",
                       "आज ही कदम उठाएँ: तुरंत अपने KVK या कृषि अधिकारी से संपर्क करें। यह रोग कुछ ही दिनों में पूरा खेत बर्बाद कर सकता है।",
                       "आजच कृती करा: ताबडतोब तुमच्या KVK किंवा कृषी अधिकाऱ्यांशी संपर्क साधा. हा रोग काही दिवसांत संपूर्ण शेत उद्ध्वस्त करू शकतो."),
 "do_ventilate": t("Improve air flow: remove extra branches, keep plants well spaced, and open the vents if you grow in a poly-house.",
                   "हवा का आना-जाना बढ़ाएँ: फालतू डालियाँ हटाएँ, पौधों में उचित दूरी रखें, पॉलीहाउस में हवा के रास्ते खोलें।",
                   "हवा खेळती ठेवा: अनावश्यक फांद्या काढा, झाडांमध्ये योग्य अंतर ठेवा, पॉलीहाऊस असल्यास झडपा उघड्या ठेवा."),
 "do_whitefly": t("Control whiteflies: put up yellow sticky traps and keep seedlings under insect-proof net.",
                  "सफ़ेद मक्खी पर नियंत्रण रखें: पीले चिपचिपे जाल लगाएँ और नर्सरी को कीट-रोधी जाली के नीचे रखें।",
                  "पांढऱ्या माशीचे नियंत्रण करा: पिवळे चिकट सापळे लावा आणि रोपवाटिका कीटकरोधक जाळीखाली ठेवा."),
 "do_wash_tools": t("Wash your hands with soap and clean tools before touching healthy plants.",
                    "स्वस्थ पौधों को छूने से पहले हाथ साबुन से धोएँ और औज़ार साफ़ करें।",
                    "निरोगी झाडांना हात लावण्यापूर्वी साबणाने हात धुवा आणि अवजारे स्वच्छ करा."),
 "do_check_underside": t("Look under the leaf with a magnifying glass for tiny mites and fine webs.",
                         "पत्ती के नीचे आवर्धक लेंस से छोटे कण (माइट) और बारीक जाले देखें।",
                         "पानाच्या खालच्या बाजूला भिंगाने बारीक कोळी (माइट) आणि जाळी तपासा."),
 "do_mites_water": t("A strong spray of plain water under the leaves reduces mites. Avoid strong insecticides without advice; they kill helpful insects.",
                     "पत्तियों के नीचे सादे पानी की तेज़ धार से कण कम होते हैं। सलाह के बिना तेज़ कीटनाशक न डालें; इससे मित्र कीट मर जाते हैं।",
                     "पानांच्या खालच्या बाजूला साध्या पाण्याचा जोरदार फवारा मारल्याने कोळी कमी होतात. सल्ल्याशिवाय जहाल कीटकनाशके वापरू नका; त्यामुळे मित्र कीटक मरतात."),
 "do_remove_mummies": t("Remove and destroy shrivelled black berries and fallen infected leaves.",
                        "सिकुड़े हुए काले दाने और गिरी हुई संक्रमित पत्तियाँ हटाकर नष्ट कर दें।",
                        "सुकलेली काळी द्राक्षे आणि गळून पडलेली बाधित पाने गोळा करून नष्ट करा."),
 "do_mark_vines": t("Mark the affected vines and keep watching them. This trunk disease has no cure; badly affected vines may have to be removed.",
                    "प्रभावित बेलों पर निशान लगाकर निगरानी रखें। इस तने के रोग का कोई इलाज नहीं है; बहुत प्रभावित बेलें हटानी पड़ सकती हैं।",
                    "बाधित वेलींवर खूण करून लक्ष ठेवा. खोडाच्या या रोगावर इलाज नाही; जास्त बाधित वेली काढाव्या लागू शकतात."),
 "do_monitor": t("Check the field every 2–3 days. Take a new photo if the spots spread.",
                 "हर 2–3 दिन में खेत देखें। धब्बे बढ़ें तो नया फोटो लें।",
                 "दर २–३ दिवसांनी शेताची पाहणी करा. ठिपके वाढले तर नवीन फोटो काढा."),
 "do_healthy": t("The leaf looks healthy. Keep up good care and keep checking regularly.",
                 "पत्ती स्वस्थ दिखती है। अच्छी देखभाल जारी रखें और नियमित जाँच करते रहें।",
                 "पान निरोगी दिसते. चांगली काळजी चालू ठेवा आणि नियमित तपासणी करत रहा."),
 "do_rust_mild": t("Common rust is often mild. If many leaves are covered, ask your KVK whether any treatment is needed.",
                   "कॉमन रस्ट अक्सर हल्का होता है। अगर बहुत सी पत्तियाँ ढक जाएँ तो KVK से पूछें कि इलाज की ज़रूरत है या नहीं।",
                   "तांबेरा बऱ्याचदा सौम्य असतो. जास्त पानांवर पसरला तर उपचारांची गरज आहे का, हे KVK ला विचारा."),
 "do_potato_tubers": t("Do not store tubers from infected plants; they can rot in storage and spread the disease.",
                       "संक्रमित पौधों के कंद भंडारण में न रखें; वे सड़ सकते हैं और रोग फैला सकते हैं।",
                       "बाधित झाडांचे कंद साठवू नका; ते साठवणीत सडून रोग पसरवू शकतात."),
 # ---- prevention
 "pv_rotate": t("Rotate crops: do not grow the same crop family in the same field every season.",
                "फसल चक्र अपनाएँ: हर मौसम में एक ही परिवार की फसल उसी खेत में न लगाएँ।",
                "पीक फेरपालट करा: दरवर्षी एकाच कुळातील पीक त्याच शेतात घेऊ नका."),
 "pv_seed": t("Use certified, disease-free seed or healthy seedlings.",
              "प्रमाणित, रोग-मुक्त बीज या स्वस्थ पौध का उपयोग करें।",
              "प्रमाणित, रोगमुक्त बियाणे किंवा निरोगी रोपे वापरा."),
 "pv_spacing": t("Keep proper spacing and stake plants so leaves dry quickly after rain or dew.",
                 "उचित दूरी रखें और पौधों को सहारा दें ताकि बारिश या ओस के बाद पत्तियाँ जल्दी सूखें।",
                 "योग्य अंतर ठेवा आणि झाडांना आधार द्या, म्हणजे पाऊस किंवा दवानंतर पाने लवकर सुकतील."),
 "pv_residue": t("After harvest, clear or plough in crop residue so the disease cannot survive on it.",
                 "कटाई के बाद फसल के अवशेष हटा दें या जुताई में दबा दें ताकि रोग उन पर जीवित न रहे।",
                 "काढणीनंतर पिकाचे अवशेष काढून टाका किंवा नांगरून गाडा, म्हणजे रोग त्यावर टिकणार नाही."),
 "pv_resistant": t("Ask your KVK for resistant or tolerant varieties or hybrids.",
                   "KVK से रोग-रोधी या सहनशील किस्में/संकर बीज के बारे में पूछें।",
                   "KVK कडून रोगप्रतिकारक किंवा सहनशील वाण/संकरित बियाण्यांची माहिती घ्या."),
 "pv_nutrition": t("Give balanced fertiliser and enough water; stressed plants fall sick more easily.",
                   "संतुलित खाद और पर्याप्त पानी दें; कमज़ोर पौधे जल्दी बीमार होते हैं।",
                   "संतुलित खत आणि पुरेसे पाणी द्या; ताण असलेली झाडे लवकर आजारी पडतात."),
 "pv_weeds": t("Remove weeds in and around the field; they can host pests and viruses.",
               "खेत और उसके आसपास के खरपतवार हटाएँ; उन पर कीट और विषाणु पनपते हैं।",
               "शेतातील व बांधावरील तण काढा; त्यावर कीड व विषाणू वाढतात."),
 "pv_mulch": t("Mulch the soil so rain does not splash soil and spores onto the leaves.",
               "मिट्टी पर मल्च बिछाएँ ताकि बारिश की छींटों से मिट्टी और बीजाणु पत्तियों पर न उछलें।",
               "जमिनीवर मल्चिंग करा, म्हणजे पावसाच्या थेंबांबरोबर माती व बीजाणू पानांवर उडणार नाहीत."),
 "pv_scout": t("Check your plants often, especially in cool, humid or rainy weather.",
               "पौधों की नियमित जाँच करें, ख़ासकर ठंडे, नम या बारिश के मौसम में।",
               "झाडांची वारंवार पाहणी करा, विशेषतः थंड, दमट किंवा पावसाळी हवामानात."),
 "pv_canopy": t("Prune and train vines to open the canopy so leaves and bunches dry quickly.",
                "बेलों की छँटाई और प्रशिक्षण करें ताकि पत्तियाँ और गुच्छे जल्दी सूखें।",
                "वेलींची छाटणी व वळण देऊन छत्र मोकळे ठेवा, म्हणजे पाने व घड लवकर सुकतील."),
 "pv_wound": t("Protect pruning wounds and prune in dry weather.",
               "छँटाई के घावों को सुरक्षित रखें और सूखे मौसम में छँटाई करें।",
               "छाटणीच्या जखमांचे संरक्षण करा आणि कोरड्या हवामानात छाटणी करा."),
 "pv_nursery": t("Raise seedlings in a clean, covered nursery and check them before transplanting.",
                 "पौध साफ़, ढकी हुई नर्सरी में तैयार करें और रोपाई से पहले जाँच लें।",
                 "रोपे स्वच्छ, झाकलेल्या रोपवाटिकेत तयार करा आणि लागवडीपूर्वी तपासा."),
}

def cls(id, crop, typ, urg, name, see, do, pv):
    return {"id": id, "crop": crop, "type": typ, "urgency": urg, "name": name, "see": see, "do": do, "prevent": pv}

H = lambda cid, crop: cls(cid, crop, "healthy", "none",
        t("Healthy leaf", "स्वस्थ पत्ती", "निरोगी पान"),
        t("No clear spots, mould, curling or insects.", "कोई साफ़ धब्बा, फफूंद, मुड़ाव या कीट नहीं दिखता।", "स्पष्ट ठिपके, बुरशी, वाकडेपणा किंवा कीड दिसत नाही."),
        ["do_healthy"], ["pv_scout", "pv_nutrition"])

classes = [
 cls("Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot", "corn", "fungal", "medium",
     t("Gray leaf spot", "ग्रे लीफ स्पॉट (धूसर पत्ती धब्बा)", "राखाडी पानांवरील ठिपके (ग्रे लीफ स्पॉट)"),
     t("Narrow, rectangular grey-brown spots that run along the leaf veins.", "पत्ती की नसों के साथ पतले, आयताकार भूरे-धूसर धब्बे।", "पानाच्या शिरांच्या दिशेने लांबट, आयताकृती राखाडी-तपकिरी ठिपके."),
     ["do_monitor", "do_expert"], ["pv_residue", "pv_rotate", "pv_resistant"]),
 cls("Corn_(maize)___Common_rust_", "corn", "fungal", "low",
     t("Common rust", "कॉमन रस्ट (रतुआ)", "तांबेरा (कॉमन रस्ट)"),
     t("Small, raised reddish-brown powdery bumps on both sides of the leaf.", "पत्ती के दोनों ओर छोटे, उभरे हुए लाल-भूरे चूर्ण जैसे दाने।", "पानाच्या दोन्ही बाजूंना लहान, उंचवट्यासारखे लालसर-तपकिरी भुकटीदार ठिपके."),
     ["do_rust_mild", "do_monitor"], ["pv_resistant", "pv_scout"]),
 cls("Corn_(maize)___Northern_Leaf_Blight", "corn", "fungal", "medium",
     t("Northern leaf blight", "नॉर्दर्न लीफ ब्लाइट (उत्तरी पत्ती झुलसा)", "नॉर्दर्न लीफ ब्लाइट (पानांवरील करपा)"),
     t("Long, cigar-shaped grey-green to tan patches on the leaf.", "पत्ती पर लंबे, सिगार जैसे धूसर-हरे से भूरे धब्बे।", "पानावर लांब, सिगारसारखे राखाडी-हिरवे ते तपकिरी चट्टे."),
     ["do_monitor", "do_expert"], ["pv_resistant", "pv_residue", "pv_rotate"]),
 H("Corn_(maize)___healthy", "corn"),

 cls("Grape___Black_rot", "grape", "fungal", "high",
     t("Black rot", "ब्लैक रॉट (काला सड़न)", "काळी कुज (ब्लॅक रॉट)"),
     t("Small brown round spots with a dark edge on leaves; berries shrivel into hard black balls.", "पत्तियों पर गहरे किनारे वाले छोटे गोल भूरे धब्बे; दाने सिकुड़कर कठोर काले हो जाते हैं।", "पानांवर गडद कडा असलेले लहान गोल तपकिरी ठिपके; द्राक्षे सुकून कडक काळी होतात."),
     ["do_remove_mummies", "do_expert"], ["pv_canopy", "pv_residue", "pv_scout"]),
 cls("Grape___Esca_(Black_Measles)", "grape", "fungal", "medium",
     t("Esca (black measles)", "एस्का (ब्लैक मीज़ल्स)", "एस्का (ब्लॅक मीझल्स)"),
     t("Yellow or red stripes between the veins that turn brown ('tiger stripes'); dark spots on berries.", "नसों के बीच पीली या लाल धारियाँ जो भूरी हो जाती हैं ('बाघ की धारियाँ'); दानों पर काले धब्बे।", "शिरांमधील पिवळे किंवा लाल पट्टे जे तपकिरी होतात ('वाघाच्या पट्ट्यांसारखे'); द्राक्षांवर काळे ठिपके."),
     ["do_mark_vines", "do_expert"], ["pv_wound", "pv_canopy"]),
 cls("Grape___Leaf_blight_(Isariopsis_Leaf_Spot)", "grape", "fungal", "medium",
     t("Leaf blight (Isariopsis leaf spot)", "पत्ती झुलसा (इसारियोप्सिस धब्बा)", "पानांवरील करपा (इसारियोप्सिस ठिपके)"),
     t("Irregular dark-brown spots, mostly on older leaves; leaves may dry and fall.", "पुरानी पत्तियों पर अनियमित गहरे भूरे धब्बे; पत्तियाँ सूखकर गिर सकती हैं।", "जुन्या पानांवर अनियमित गडद तपकिरी ठिपके; पाने सुकून गळू शकतात."),
     ["do_remove_leaves", "do_expert"], ["pv_canopy", "pv_residue", "pv_scout"]),
 H("Grape___healthy", "grape"),

 cls("Pepper,_bell___Bacterial_spot", "pepper", "bacterial", "medium",
     t("Bacterial spot", "जीवाणु पत्ती धब्बा (बैक्टीरियल स्पॉट)", "जिवाणूजन्य ठिपके (बॅक्टेरियल स्पॉट)"),
     t("Small water-soaked spots that turn brown and rough; leaves may yellow and drop.", "छोटे पानी जैसे धब्बे जो भूरे और खुरदुरे हो जाते हैं; पत्तियाँ पीली होकर गिर सकती हैं।", "लहान पाणथळ ठिपके जे तपकिरी व खरबरीत होतात; पाने पिवळी पडून गळू शकतात."),
     ["do_remove_leaves", "do_no_wet_work", "do_expert"], ["pv_seed", "pv_rotate", "pv_nursery"]),
 H("Pepper,_bell___healthy", "pepper"),

 cls("Potato___Early_blight", "potato", "fungal", "medium",
     t("Early blight", "अगेती झुलसा (अर्ली ब्लाइट)", "लवकर येणारा करपा (अर्ली ब्लाइट)"),
     t("Brown spots with ring-like lines (like a target), starting on the older, lower leaves.", "छल्लेदार रेखाओं वाले भूरे धब्बे (निशाने जैसे), पहले नीचे की पुरानी पत्तियों पर।", "वर्तुळाकार रेषा असलेले तपकिरी ठिपके (नेमबाजीच्या लक्ष्यासारखे), आधी खालच्या जुन्या पानांवर."),
     ["do_remove_leaves", "do_water_base", "do_expert"], ["pv_rotate", "pv_nutrition", "pv_seed"]),
 cls("Potato___Late_blight", "potato", "fungal", "high",
     t("Late blight", "पछेती झुलसा (लेट ब्लाइट)", "उशिरा येणारा करपा (लेट ब्लाइट)"),
     t("Large, dark, greasy-looking patches; white fuzzy growth underneath in humid weather. Spreads very fast in cool, wet weather.", "बड़े, गहरे, चिकने से दिखने वाले धब्बे; नमी में नीचे सफ़ेद रुई जैसी परत। ठंडे, गीले मौसम में बहुत तेज़ी से फैलता है।", "मोठे, गडद, तेलकट दिसणारे चट्टे; दमट हवामानात खालच्या बाजूला पांढरी बुरशी. थंड, ओल्या हवामानात खूप वेगाने पसरतो."),
     ["do_expert_urgent", "do_destroy_plants", "do_potato_tubers"], ["pv_seed", "pv_resistant", "pv_scout"]),
 H("Potato___healthy", "potato"),

 cls("Tomato___Bacterial_spot", "tomato", "bacterial", "medium",
     t("Bacterial spot", "जीवाणु पत्ती धब्बा (बैक्टीरियल स्पॉट)", "जिवाणूजन्य ठिपके (बॅक्टेरियल स्पॉट)"),
     t("Many small dark, water-soaked spots on leaves; rough scabby spots on fruit.", "पत्तियों पर कई छोटे गहरे, पानी जैसे धब्बे; फलों पर खुरदुरे पपड़ीदार धब्बे।", "पानांवर अनेक लहान गडद, पाणथळ ठिपके; फळांवर खरबरीत खपल्यांसारखे ठिपके."),
     ["do_remove_leaves", "do_no_wet_work", "do_water_base", "do_expert"], ["pv_seed", "pv_rotate", "pv_nursery"]),
 cls("Tomato___Early_blight", "tomato", "fungal", "medium",
     t("Early blight", "अगेती झुलसा (अर्ली ब्लाइट)", "लवकर येणारा करपा (अर्ली ब्लाइट)"),
     t("Brown spots with ring-like lines (like a target) on older leaves, with yellowing around them.", "पुरानी पत्तियों पर छल्लेदार रेखाओं वाले भूरे धब्बे (निशाने जैसे), चारों ओर पीलापन।", "जुन्या पानांवर वर्तुळाकार रेषा असलेले तपकिरी ठिपके, भोवती पिवळसरपणा."),
     ["do_remove_leaves", "do_water_base", "do_expert"], ["pv_rotate", "pv_mulch", "pv_nutrition", "pv_spacing"]),
 cls("Tomato___Late_blight", "tomato", "fungal", "high",
     t("Late blight", "पछेती झुलसा (लेट ब्लाइट)", "उशिरा येणारा करपा (लेट ब्लाइट)"),
     t("Large, dark, greasy-looking patches on leaves and stems; white fuzzy growth underneath in humid weather. Spreads very fast in cool, wet weather.", "पत्तियों और तनों पर बड़े, गहरे, चिकने से धब्बे; नमी में नीचे सफ़ेद रुई जैसी परत। ठंडे, गीले मौसम में बहुत तेज़ी से फैलता है।", "पाने व खोडांवर मोठे, गडद, तेलकट चट्टे; दमट हवामानात खालच्या बाजूला पांढरी बुरशी. थंड, ओल्या हवामानात खूप वेगाने पसरतो."),
     ["do_expert_urgent", "do_destroy_plants", "do_water_base"], ["pv_seed", "pv_spacing", "pv_scout"]),
 cls("Tomato___Leaf_Mold", "tomato", "fungal", "medium",
     t("Leaf mould", "पत्ती फफूंद (लीफ मोल्ड)", "पानांवरील बुरशी (लीफ मोल्ड)"),
     t("Pale yellow patches on top of the leaf with olive-green to grey velvety mould underneath. Common in humid, closed spaces.", "पत्ती के ऊपर हल्के पीले धब्बे और नीचे जैतूनी-हरी से धूसर मखमली फफूंद। नम, बंद जगहों में आम।", "पानाच्या वरच्या बाजूला फिकट पिवळे ठिपके व खाली जैतुनी-हिरवी ते राखाडी मखमली बुरशी. दमट, बंदिस्त जागी सामान्य."),
     ["do_ventilate", "do_remove_leaves", "do_expert"], ["pv_spacing", "pv_resistant", "pv_scout"]),
 cls("Tomato___Septoria_leaf_spot", "tomato", "fungal", "medium",
     t("Septoria leaf spot", "सेप्टोरिया पत्ती धब्बा", "सेप्टोरिया पानावरील ठिपके"),
     t("Many small round spots with grey-white centres and dark edges, usually on lower leaves.", "छोटे गोल धब्बे जिनका केंद्र धूसर-सफ़ेद और किनारा गहरा होता है, आमतौर पर नीचे की पत्तियों पर।", "लहान गोल ठिपके, मध्य राखाडी-पांढरा व कडा गडद, सहसा खालच्या पानांवर."),
     ["do_remove_leaves", "do_no_wet_work", "do_expert"], ["pv_rotate", "pv_mulch", "pv_spacing"]),
 cls("Tomato___Spider_mites Two-spotted_spider_mite", "tomato", "pest", "medium",
     t("Spider mites", "मकड़ी कण (स्पाइडर माइट)", "कोळी (स्पायडर माइट)"),
     t("Tiny yellow dots on leaves, turning bronze; fine webbing under the leaf. Common in hot, dry weather.", "पत्तियों पर छोटे पीले बिंदु जो काँसे जैसे हो जाते हैं; पत्ती के नीचे बारीक जाले। गर्म, सूखे मौसम में आम।", "पानांवर लहान पिवळे ठिपके जे कांस्य रंगाचे होतात; पानाखाली बारीक जाळी. उष्ण, कोरड्या हवामानात सामान्य."),
     ["do_check_underside", "do_mites_water", "do_expert"], ["pv_nutrition", "pv_weeds", "pv_scout"]),
 cls("Tomato___Target_Spot", "tomato", "fungal", "medium",
     t("Target spot", "टारगेट स्पॉट", "टार्गेट स्पॉट (वर्तुळाकार ठिपके)"),
     t("Brown spots with ring-like lines and a yellow edge; can also mark the fruit.", "छल्लेदार रेखाओं और पीले किनारे वाले भूरे धब्बे; फलों पर भी निशान पड़ सकते हैं।", "वर्तुळाकार रेषा व पिवळ्या कडा असलेले तपकिरी ठिपके; फळांवरही डाग पडू शकतात."),
     ["do_remove_leaves", "do_ventilate", "do_expert"], ["pv_rotate", "pv_spacing", "pv_residue"]),
 cls("Tomato___Tomato_Yellow_Leaf_Curl_Virus", "tomato", "viral", "high",
     t("Yellow leaf curl virus", "पीली पत्ती मरोड़ विषाणु (लीफ कर्ल वायरस)", "पिवळी पाने गुंडाळणारा विषाणू (लीफ कर्ल वायरस)"),
     t("Leaves turn yellow and curl upward, become small; plants are stunted. Spread by whiteflies.", "पत्तियाँ पीली होकर ऊपर की ओर मुड़ती हैं और छोटी रह जाती हैं; पौधे बौने रह जाते हैं। सफ़ेद मक्खी से फैलता है।", "पाने पिवळी पडून वरच्या बाजूला गुंडाळली जातात व लहान राहतात; झाडांची वाढ खुंटते. पांढऱ्या माशीमुळे पसरतो."),
     ["do_destroy_plants", "do_whitefly", "do_expert"], ["pv_nursery", "pv_weeds", "pv_resistant"]),
 cls("Tomato___Tomato_mosaic_virus", "tomato", "viral", "high",
     t("Mosaic virus", "मोज़ेक विषाणु", "मोझॅक विषाणू"),
     t("Light and dark green patches (mosaic) on leaves, twisted or narrow leaves, slow growth. Spreads by touch and tools.", "पत्तियों पर हल्के-गहरे हरे धब्बे (मोज़ेक), मुड़ी या पतली पत्तियाँ, धीमी बढ़वार। छूने और औज़ारों से फैलता है।", "पानांवर फिकट-गडद हिरवे ठिपके (मोझॅक), वळलेली किंवा अरुंद पाने, वाढ मंदावते. स्पर्श व अवजारांमुळे पसरतो."),
     ["do_destroy_plants", "do_wash_tools", "do_expert"], ["pv_seed", "pv_weeds", "pv_nursery"]),
 H("Tomato___healthy", "tomato"),
]

classes.append(cls("Other___not_covered", "other", "other", "none",
    t("Not a covered crop leaf", "समर्थित फसल की पत्ती नहीं", "समर्थित पिकाचे पान नाही"),
    t("", "", ""), [], []))
ui = {
 "app_name": t("Pik Doctor", "पीक डॉक्टर", "पीक डॉक्टर"),
 "tagline": t("Check a crop leaf. Works with no internet.", "फसल की पत्ती जाँचें। बिना इंटरनेट के चलता है।", "पिकाचे पान तपासा. इंटरनेटशिवाय चालते."),
 "online": t("Online", "ऑनलाइन", "ऑनलाइन"),
 "offline": t("Offline: fully working", "ऑफ़लाइन: पूरी तरह चालू", "ऑफलाइन: पूर्णपणे चालू"),
 "model_loading": t("Loading the model…", "मॉडल लोड हो रहा है…", "मॉडेल लोड होत आहे…"),
 "model_ready": t("Ready on this phone", "इस फ़ोन पर तैयार", "या फोनवर तयार"),
 "which_crop": t("Which crop?", "कौन सी फसल?", "कोणते पीक?"),
 "crop_auto": t("Not sure (auto)", "पता नहीं (अपने आप)", "माहीत नाही (आपोआप)"),
 "take_photo": t("Take a photo", "फोटो लें", "फोटो काढा"),
 "choose_photo": t("Choose from gallery", "गैलरी से चुनें", "गॅलरीमधून निवडा"),
 "photo_tip": t("Tip: put one leaf on a plain background in daylight and fill the frame.", "सुझाव: दिन की रोशनी में एक पत्ती को सादी पृष्ठभूमि पर रखें और फ़्रेम में पूरी भरें।", "सूचना: दिवसाच्या प्रकाशात एकच पान साध्या पार्श्वभूमीवर ठेवा आणि फ्रेम भरून घ्या."),
 "covered": t("Covers tomato, grape, maize, potato and bell pepper.", "टमाटर, अंगूर, मक्का, आलू और शिमला मिर्च के लिए।", "टोमॅटो, द्राक्ष, मका, बटाटा व ढोबळी मिरचीसाठी."),
 "checking": t("Checking the leaf…", "पत्ती की जाँच हो रही है…", "पान तपासले जात आहे…"),
 "result": t("Result", "नतीजा", "निकाल"),
 "confidence": t("Confidence", "भरोसा", "खात्री"),
 "not_sure_title": t("Not sure. Please retake the photo.", "पक्का नहीं। कृपया दोबारा फोटो लें।", "खात्री नाही. कृपया पुन्हा फोटो काढा."),
 "not_sure_body": t("The app cannot tell clearly. Take a closer, brighter photo of one leaf. If the problem continues, show the plant to your KVK or agriculture officer.", "ऐप साफ़ नहीं बता पा रहा। एक पत्ती का पास से, रोशनी में फोटो लें। समस्या बनी रहे तो पौधा अपने KVK या कृषि अधिकारी को दिखाएँ।", "अॅप स्पष्ट सांगू शकत नाही. एका पानाचा जवळून, उजेडात फोटो काढा. समस्या कायम राहिली तर झाड KVK किंवा कृषी अधिकाऱ्यांना दाखवा."),
 "best_guess": t("Best guess so far:", "अभी तक का सबसे संभावित:", "आतापर्यंतचा संभाव्य अंदाज:"),
 "other_possible": t("Other possibilities", "अन्य संभावनाएँ", "इतर शक्यता"),
 "what_see": t("What it looks like", "यह कैसा दिखता है", "हे कसे दिसते"),
 "what_do": t("What to do now", "अभी क्या करें", "आता काय करावे"),
 "how_prevent": t("How to prevent it", "इसे कैसे रोकें", "प्रतिबंध कसा करावा"),
 "get_help": t("Get expert help", "विशेषज्ञ की मदद लें", "तज्ज्ञांची मदत घ्या"),
 "kcc": t("Kisan Call Centre: 1800-180-1551 (toll free)", "किसान कॉल सेंटर: 1800-180-1551 (टोल फ़्री)", "किसान कॉल सेंटर: 1800-180-1551 (टोल फ्री)"),
 "disclaimer": t("This is a screening aid, not a final diagnosis. Confirm with an agriculture expert before you spray anything.", "यह जाँच में सहायता है, अंतिम निदान नहीं। कोई भी दवा छिड़कने से पहले कृषि विशेषज्ञ से पुष्टि करें।", "ही तपासणीसाठी मदत आहे, अंतिम निदान नाही. कोणतीही फवारणी करण्यापूर्वी कृषी तज्ज्ञांकडून खात्री करा."),
 "listen": t("Listen", "सुनें", "ऐका"),
 "stop": t("Stop", "रोकें", "थांबवा"),
 "no_voice": t("This phone has no voice for this language. Install it in the phone's text-to-speech settings.", "इस फ़ोन में इस भाषा की आवाज़ नहीं है। फ़ोन की टेक्स्ट-टू-स्पीच सेटिंग में इसे इंस्टॉल करें।", "या फोनमध्ये या भाषेचा आवाज नाही. फोनच्या टेक्स्ट-टू-स्पीच सेटिंगमध्ये तो इन्स्टॉल करा."),
 "history": t("Past checks (saved on this phone)", "पिछली जाँचें (इसी फ़ोन में सहेजी)", "मागील तपासण्या (याच फोनमध्ये साठवलेल्या)"),
 "history_empty": t("No checks yet.", "अभी कोई जाँच नहीं।", "अजून कोणतीही तपासणी नाही."),
 "clear": t("Clear", "मिटाएँ", "पुसा"),
 "again": t("Check another leaf", "दूसरी पत्ती जाँचें", "दुसरे पान तपासा"),
 "install": t("Install app", "ऐप इंस्टॉल करें", "अॅप इन्स्टॉल करा"),
 "error": t("Could not read this photo. Please try again.", "यह फोटो पढ़ा नहीं जा सका। कृपया दोबारा कोशिश करें।", "हा फोटो वाचता आला नाही. कृपया पुन्हा प्रयत्न करा."),
 "other_title": t("This does not look like a covered crop leaf", "यह किसी समर्थित फसल की पत्ती नहीं लगती", "हे समर्थित पिकाचे पान दिसत नाही"),
 "other_body": t("Pik Doctor covers tomato, grape, maize, potato and bell pepper leaves. Take a close photo of one leaf of these crops, or ask your KVK about other crops.", "पीक डॉक्टर टमाटर, अंगूर, मक्का, आलू और शिमला मिर्च की पत्तियाँ जाँचता है। इन फसलों की एक पत्ती का पास से फोटो लें, या दूसरी फसलों के लिए KVK से पूछें।", "पीक डॉक्टर टोमॅटो, द्राक्ष, मका, बटाटा व ढोबळी मिरचीची पाने तपासतो. या पिकांपैकी एका पानाचा जवळून फोटो काढा, किंवा इतर पिकांसाठी KVK ला विचारा."),
 "healthy_word": t("Healthy", "स्वस्थ", "निरोगी"),
 "types": {
   "fungal": t("Fungal disease", "फफूंद जनित रोग", "बुरशीजन्य रोग"),
   "bacterial": t("Bacterial disease", "जीवाणु जनित रोग", "जिवाणूजन्य रोग"),
   "viral": t("Viral disease", "विषाणु जनित रोग", "विषाणूजन्य रोग"),
   "pest": t("Pest attack (mites)", "कीट प्रकोप (माइट)", "किडीचा प्रादुर्भाव (कोळी)"),
   "healthy": t("Healthy", "स्वस्थ", "निरोगी")},
 "urgency": {
   "high": t("Act today", "आज ही कदम उठाएँ", "आजच कृती करा"),
   "medium": t("Act this week", "इसी सप्ताह कार्रवाई करें", "याच आठवड्यात कृती करा"),
   "low": t("Keep watching", "निगरानी रखें", "लक्ष ठेवा"),
   "none": t("All good", "सब ठीक", "सर्व ठीक")},
}

kb = {"crops": crops, "snippets": S, "classes": classes, "ui": ui}
out = os.path.join(os.path.dirname(__file__), '..', 'app', 'data', 'kb.json')
json.dump(kb, open(out, 'w'), ensure_ascii=False, indent=1)
# sanity: every snippet id exists, 3 languages everywhere
for c in classes:
    for k in c['do'] + c['prevent']: assert k in S, k
def chk(o):
    if isinstance(o, dict):
        if set(o) == {"en","hi","mr"}: assert all(o.values()) or not any(o.values()); return
        for v in o.values(): chk(v)
    elif isinstance(o, list):
        for v in o: chk(v)
chk(kb); print('kb ok:', len(classes), 'classes,', len(S), 'snippets')
